language: php

php:
    - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - openssl aes-256-cbc -K $encrypted_d4931f6d241c_key -iv $encrypted_d4931f6d241c_iv -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
    - composer self-update
    - composer install

script:
    - ./psh unit

after_success:
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./psh build; fi
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./deploy.sh; fi
